spring.application.name=dashboard
server.port=5000

spring.data.mongodb.uri=mongodb://localhost:27017/siem_dashboard

# Allows bigger JSON payloads from the response agent if needed.
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB